language: minimal
sudo: required
services:
- docker
before_script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
script:
- make push
env:
  global:
  - secure: mLfNTkagxp3p+ZmpdumwD5PEPFieuouMB7e5yk0vFk2nKHZdSHJhgWcWLXBsKIcjQEH7MET1/UO8MPa+T8hXodXNn1BgO3tcp+KXJy6k5TUnznDd+KPzPnN+VbOG440sf71YDqjOm38RwQm00Wc5pmNzUAU2BbJAG3QcrCHr8JoTkUWvbn9p3MKpKelUUn/W45AdjuBA8hcZLgK3vFlImhoIIhTAha0+lhfj8CkX0XMdyxf2kJgz+682bMmzv4mlbrLtNCOa1alxm/6TZpbiC+KZkMf90yPrhR8hYTUA5gGbZJ6/oVh6/fnb+QapqLr4T1oEvlUsaovq6WvA+npFAiGJmjlWd0Z3wGVyBhViXogPrIQeom0Si6FU8w7SB/eZ2BjtKyBrcxiCfvCT77pJM99kO96K58ivQIgsnpxmgmu8Z/Ks06hgph05HHClw/GQBQzV4UpLoGW/MLeSSIP9HjqO6n3Anl+MbIXIYt/+RQfx0uOfQWuGzXMGJ15wiy+9K2mMmDMsjALBUVtgtyFH4LIvnKfLBTG2xU9ZzhZsa4PceOTBCzO9saEP+nXql6H1xNmbhuzbFp+nZMPpkwbnrSU8CmI5jXYq0m8k+bRVCoR1B1mypPJPF50gN3mMmkbTx5IvJUSWtM1HfQiOZoZ6j7O73hWlV5dTgA3FXBYZLok=
  - secure: KJ2jxmqvayl9ve4ydudDhjxRVrbkORoLqz5plQEJ6h1foXzclvZ49zpZ1Le1rusQI/1TE/2vpglkjqcZ2YhiuMESQeml+6HvB4Ad3yJRCCh/uUkUEFNNhCfJAeYJcMe53br4xRaFXIdU9IMVAQTAo73aBZzS5atNKkiXZKDqgHSu+LbdeoqIJ6pxewzVOwzbheyB/TYwffVhy8iGH39XILWyfbIkn7w3eXXjKvq4ccFNRngyE644Bz4NilZiDL37X/96om5Mq+sKe46bzSNl9JJiAHDgKNjxfFoyVYQuupxLLpg3WLJtoZvTP0UUdzywj+x9+cbYYvYYrTGDpz/LnLoMtJ9kdaNcqOPBN1oVrZs/W45lSAgNhTbUD8elVK2bidEHeLTRp5HdZFldJl2+jQDT0IOa3RTvgoHWoabcqYkKPwMko0n4d58VlE3VI76OwgiwHGbWNbFX6vjIF9Yq/nPFjYyARw//M+fbg85XnW6UrPmCn1LDg5zyj+czH8HoN/WLTfeJKvyre5HLvz63WA2M1cQwfjOlb3c5M/RHnopDHlzC8g90/vq6Hzsk8rK8IbdNhck7BNaNWRnB0ASV9nr4yadA2jTOPXOWHEUfembfAua3pyx5Puzo7kAGpJKfIqGtVvrc/h9zDJ3hGdbvn0a8E63UCYU4tAGFac3auHw=
