language: minimal
sudo: required
services:
- docker
before_script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
script:
- make push
env:
  global:
  - secure: KJ2jxmqvayl9ve4ydudDhjxRVrbkORoLqz5plQEJ6h1foXzclvZ49zpZ1Le1rusQI/1TE/2vpglkjqcZ2YhiuMESQeml+6HvB4Ad3yJRCCh/uUkUEFNNhCfJAeYJcMe53br4xRaFXIdU9IMVAQTAo73aBZzS5atNKkiXZKDqgHSu+LbdeoqIJ6pxewzVOwzbheyB/TYwffVhy8iGH39XILWyfbIkn7w3eXXjKvq4ccFNRngyE644Bz4NilZiDL37X/96om5Mq+sKe46bzSNl9JJiAHDgKNjxfFoyVYQuupxLLpg3WLJtoZvTP0UUdzywj+x9+cbYYvYYrTGDpz/LnLoMtJ9kdaNcqOPBN1oVrZs/W45lSAgNhTbUD8elVK2bidEHeLTRp5HdZFldJl2+jQDT0IOa3RTvgoHWoabcqYkKPwMko0n4d58VlE3VI76OwgiwHGbWNbFX6vjIF9Yq/nPFjYyARw//M+fbg85XnW6UrPmCn1LDg5zyj+czH8HoN/WLTfeJKvyre5HLvz63WA2M1cQwfjOlb3c5M/RHnopDHlzC8g90/vq6Hzsk8rK8IbdNhck7BNaNWRnB0ASV9nr4yadA2jTOPXOWHEUfembfAua3pyx5Puzo7kAGpJKfIqGtVvrc/h9zDJ3hGdbvn0a8E63UCYU4tAGFac3auHw=
